spring.application.name=attendance-system
# PostgreSQL ?????
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_system
spring.datasource.username=postgres
spring.datasource.password=wj42411061
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????????? HikariCP?
spring.datasource.hikari.maximum-pool-size=10

# ???????? schema.sql ?????????????????
spring.sql.init.mode=always